import type { DirectoryClient, PromptSection } from "./directory-model";

/**
 * The directory as it stood when it moved into the portal (24 Sep 2026), carried over from the
 * team's standalone Landing Page Directory page. It is only what a fresh portal shows before the
 * first save; once `sop_pages` holds a row for the directory, that row is the truth and this file
 * is never read again. Test rows the team added while building the page are kept as they were.
 */
export const SEED_CLIENTS: DirectoryClient[] = [
    {
        name: "American River Resort",
        platform: "GoHighLevel",
        manager: "Nicole",
        doc: "https://docs.google.com/document/d/1ZWufWX9hoLWg1qV6ANtUthwGRzLHU_wBSqJWkQglIMA/edit?tab=t.0#heading=h.mruxqwudpn4g",
        instagram: "https://bio.americanriverresort.com/",
        facebook: "https://go.americanriverresort.com/booknow-650653",
        metaAds: "https://bio.americanriverresort.com/bio-step1",
        metaTags: true,
        live: true,
    },
    {
        name: "Asheville River Cabins",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/u/0/d/1Zl9Q4L9qHew0c7gSq4Ly-CH9zUrZJQaC3F0_fpbGVxc/edit",
        manager: "Charlotte",
        facebook: "https://join.ashevillerivercabins.com/booknow",
        instagram: "https://bio.ashevillerivercabins.com/booknow",
        metaAds: "https://go.ashevillerivercabins.com/signup-fb",
        tiktok: "https://links.ashevillerivercabins.com/links",
        live: true,
        metaTags: true,
    },
    {
        name: "Away2PA",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1MxOhizmJkXWMWxOAbUqWhV4_7fPjQpCJUaN-kAwzUYY/edit?tab=t.0#heading=h.mruxqwudpn4g",
        manager: "Alicia",
        facebook: "https://bio.awaytopa.com/booknow",
        metaAds: "https://bio.awaytopa.com/signup",
        instagram: "https://bio.awaytopa.com/book",
        tiktok: "https://links.awaytopa.com/book",
        live: true,
        metaTags: true,
    },
    {
        name: "AwayFrames",
        platform: "GoHighLevel",
        manager: "Alicia",
        design: "design2",
        doc: "https://docs.google.com/document/d/1fML0TS6higuGQhjZnG-UMdJkHR-sQQ49vcICwFQhpWk/edit?usp=sharing",
        facebook: "https://links.awayframes.com/booknow",
        instagram: "https://bio.awayframes.com/booknow",
        metaAds: "https://bio.awayframes.com/signupnow",
        live: true,
        metaTags: true,
    },
    {
        name: "Best Texas Travel",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1qQA82Zax4CdLXhXpRQMJizpSVHrM6tmq_ibXfoT8PH4/edit?tab=t.0",
        manager: "Nicole",
        metaAds: "https://bio.besttexastravel.com/explore",
        facebook: "https://bio.besttexastravel.com/go-383308",
        instagram: "https://bio.besttexastravel.com/booknow",
        tiktok: "https://bio.besttexastravel.com/link-631570",
        live: true,
        metaTags: true,
    },
    {
        name: "Big Moon Ranch",
        platform: "GoHighLevel",
        manager: "Charlotte",
        design: "design1",
        doc: "https://docs.google.com/document/d/1cKd_do0l0_M-Jw_bPcLFveUCkpVbtx-XFf7FTcOVhr0/edit?tab=t.0#heading=h.mruxqwudpn4g",
        instagram: "https://bio.staybigmoonranch.com/links-3399",
        facebook: "https://info.staybigmoonranch.com/bookdirect",
        metaAds: "https://info.staybigmoonranch.com/signupnow",
        metaTags: true,
        live: true,
    },
    {
        name: "Bison Ridge Retreat",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/15wV4opuHOAhZl6C91bBX_uJ5XHshfF53mmReG5F3bnM/edit?tab=t.0",
        manager: "Chiara",
        instagram: "https://bio.bisonridgeretreat.com/booknow",
        facebook: "https://bio.bisonridgeretreat.com/visitnow",
        metaAds: "https://link.bisonridgeretreat.com/booknow",
        live: true,
        metaTags: true,
    },
    {
        name: "Columbia Gorge Getaways",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1IntKNc7SMI03Ll8OV9S9mePnw_JZ6qrh9RPmvtUbySo/edit?tab=t.0#heading=h.mruxqwudpn4g",
        manager: "Chiara",
        facebook: "https://go.columbiagorgeglamping.com/visitnow",
        metaAds: "https://go.columbiagorgeglamping.com/staynow",
        instagram: "https://go.columbiagorgeglamping.com/booknow",
        live: true,
        metaTags: true,
    },
    {
        name: "Endless Stays",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/14nYpiwfmsGmCYfpXU7jDe1ijhZJDspirWrlPCcw6Lqg/edit?tab=t.0",
        manager: "Nicole",
        facebook: "https://bio.stayendless.com/book",
        instagram: "https://bio.stayendless.com/signup-406403",
        metaAds: "https://join.stayendless.com/signup-729440",
        tiktok: "https://link.stayendless.com/link",
        live: true,
        metaTags: true,
    },
    {
        name: "Evergreen Cabins",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1WAQy60AEgXUUp2qU0aVXfhgLgHOwhrniS9elg0e-LPg/edit?usp=sharing",
        manager: "Nicole",
        facebook: "https://bio.evergreencabins.co/booknow",
        instagram: "https://bio.evergreencabins.co/info-186821",
        metaAds: "https://bio.evergreencabins.co/promo",
        tiktok: "https://links.evergreencabins.co/links",
        live: true,
        metaTags: true,
    },
    {
        name: "FLOHOM",
        platform: "Netlify",
        doc: "https://docs.google.com/document/d/1AlqSu4tmF001QkVpn8gGhT0J_kumhWOoDwOCuHH9MqY/edit?usp=sharing",
        manager: "Makenna",
        facebook: "https://bio.goflohom.com/go",
        instagram: "https://bio.goflohom.com/info",
        metaAds: "https://bio.goflohom.com/join",
        tiktok: "https://links.goflohom.com/go",
        live: true,
        metaTags: true,
    },
    {
        name: "Green Springs Inn",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1haplJw1icIvN1Gw_IQJKJau5rF941LC6NTWjd-ka8GM/edit?tab=t.0#heading=h.vr0mfb2ljwi3",
        manager: "Alicia",
        facebook: "https://go.staygreenspringsinn.com/booknow",
        instagram: "https://bio.staygreenspringsinn.com/booknow",
        metaAds: "https://bio.staygreenspringsinn.com/signupnow",
        tiktok: "https://link.staygreenspringsinn.com/link",
        live: true,
        metaTags: true,
    },
    {
        name: "Hiawassee Glamping",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1zKscKJNvMSxhaD9IQK9yb_62dW0fb9UeEzHsl9FtURI/edit?tab=t.0",
        manager: "Alicia",
        facebook: "https://bio.hiawasseeglamping.com/promotion",
        instagram: "https://bio.hiawasseeglamping.com/book",
        metaAds: "https://bio.hiawasseeglamping.com/signupnow",
        tiktok: "https://links.hiawasseeglamping.com/book",
        live: true,
        metaTags: true,
    },
    {
        name: "Home Base",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/u/0/d/1WVvc8wzaK_o_uVhtND71mLUXNafWU_TJVCQr518_21Q/edit",
        manager: "Charlotte",
        facebook: "https://links.stayhomebase.com/join",
        instagram: "https://bio.stayhomebase.com/signupnow",
        metaAds: "https://go.stayhomebase.com/join",
        live: true,
        metaTags: true,
    },
    {
        name: "Inspired Retreats",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1jj63koYwcGQsSNyMd5EXAw8EJuiG9Ecsu9OqMbEX15w/edit?usp=sharing",
        manager: "Makenna",
        facebook: "https://links.stayinspiredretreats.com/go",
        instagram: "https://bio.stayinspiredretreats.com/links",
        metaAds: "https://go.stayinspiredretreats.com/links",
        live: true,
        metaTags: true,
    },
    {
        name: "Little River Landing",
        platform: "Netlify",
        doc: "https://docs.google.com/document/d/1AZI6zFOULsJ3LpFVsEqu3HxtdJ3fEmUS84uivaGPN5I/edit?usp=drive_link",
        domain: "go.staylittleriver.com",
        metaTags: true,
        live: true,
        manager: "Makenna",
    },
    {
        name: "Myrinn",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/u/0/d/1ToNy95a_fRMUjQdco_dDZ78Go-2mHWrmFNqEGiOYX2c/edit",
        manager: "Charlotte",
        facebook: "https://go.staywithmyrinn.com/book-7665",
        instagram: "https://go.staywithmyrinn.com/book",
        metaAds: "https://links.staywithmyrinn.com/book",
        tiktok: "https://links.staywithmyrinn.com/links",
        live: true,
        metaTags: true,
    },
    {
        name: "Nature Nooks Acadia",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1yJZrzPq24d2HQHPbsGXkTo3vcQT0iDFx4xyF84pngHE/edit?tab=t.0",
        manager: "Alicia",
        facebook: "https://bio.naturenooksacadia.com/signup",
        instagram: "https://bio.naturenooksacadia.com/book",
        metaAds: "https://bio.naturenooksacadia.com/booknow",
        live: true,
        metaTags: true,
    },
    {
        name: "No Domain Error Test",
        platform: "Netlify",
        manager: "Ananya",
        design: "enhanced",
        doc: "https://test.com",
        added: "2026-09-23",
    },
    {
        name: "No Master Doc Error Test",
        platform: "Netlify",
        design: "enhanced",
        domain: "testdomain.com",
        added: "2026-09-23",
    },
    {
        name: "North Star Lodge & Resort",
        platform: "Netlify",
        manager: "Charlotte",
        doc: "https://docs.google.com/document/d/1aY8dsshoIb_-S-ziJgbZlhd_dUd-oq02Q9yD5LQSnSo/edit?tab=t.0#heading=h.mruxqwudpn4g",
        domain: "go.northstarkillington.com",
        metaTags: true,
        live: true,
        facebook: "https://go.northstarkillington.com/booknow-770772",
    },
    {
        name: "Oak & Ember",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1oj1NFysbCSTxtpLEF-E87RnmJr9SRhcQPKXpNOvepxQ/edit?tab=t.0",
        manager: "Chiara",
        facebook: "https://go.stayoakandember.com/visitnow",
        metaAds: "https://go.stayoakandember.com/staynow",
        instagram: "https://go.stayoakandember.com/booknow",
        live: true,
        metaTags: true,
    },
    {
        name: "Paradise Pointe",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1aiXjYmfd_171Yu3sVjX_el231zfXj2nNmQ6j8g2M3Lc/edit?usp=sharing",
        manager: "Makenna",
        facebook: "https://bio.stayparadisepointe.com/links",
        instagram: "https://bio.stayparadisepointe.com/signup",
        metaAds: "https://go.stayparadisepointe.com/signup-fb",
        tiktok: "https://links.stayparadisepointe.com/links",
        live: true,
        metaTags: true,
    },
    {
        name: "Parker Reserve",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/u/0/d/1EQd-BPLK3Z7oPSrETfvZ3EERWzliTc0T_COjdVRWxDg/edit",
        manager: "Nicole",
        facebook: "https://go.parkerreserve.com/signup",
        instagram: "https://bio.parkerreserve.com/links",
        tiktok: "https://links.parkerreserve.com/links",
        live: true,
        metaTags: true,
    },
    {
        name: "Ponderosa Pines Resort",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1PQ5Zk5OV_etJp2MKABJkqxbYR7nVt34ByLi23z2r0-U/edit?usp=drive_link",
        manager: "Ananya",
        facebook: "https://bio.ponderosapinesresort.com/signup",
        metaAds: "https://bio.ponderosapinesresort.com/booknow-8057",
        instagram: "https://bio.ponderosapinesresort.com/booknow",
        tiktok: "https://bio.ponderosapinesresort.com/links",
        live: true,
        metaTags: true,
    },
    {
        name: "Raven Rock Mountain",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/u/0/d/1FbiTUY08OViTNEVrQiGypnF_JIM-_Um-KIisTIotsKo/edit",
        manager: "Ananya",
        facebook: "https://links.stayravenrockmountain.com/links",
        instagram: "https://info.stayravenrockmountain.com/links",
        live: true,
        metaTags: true,
    },
    {
        name: "Recently Added Test",
        platform: "GoHighLevel",
        upcoming: true,
        added: "2026-09-23",
    },
    {
        name: "Red White & Blue Views",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1v0QN4phIq7dLdUC0u5M67PDYXp0RuNk-9DJGizcjU1c/edit?tab=t.0",
        manager: "Nicole",
        instagram: "https://bio.redwhiteandblueviews.com/signup",
        facebook: "https://go.redwhiteandblueviews.com/booknow",
        metaAds: "https://bio.redwhiteandblueviews.com/promo-697915",
        tiktok: "https://bio.redwhiteandblueviews.com/links",
        live: true,
        metaTags: true,
    },
    {
        name: "Reflections Resorts",
        platform: "GoHighLevel",
        manager: "Alicia",
        doc: "https://docs.google.com/document/d/19h4QAnfIzb44bvDzDny8VwLUcvNYuq7hM3YaQAIarOs/edit?usp=sharing",
        facebook: "https://go.reflections-resorts.com/booknow",
        instagram: "https://bio.reflections-resorts.com/booknow",
        live: true,
        metaTags: true,
    },
    {
        name: "Ridge & Falls",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1jiYswjlCsDjsO1LW7f1n7GLROqEDfc2feoi8dyLKjaA/edit?usp=sharing",
        manager: "Makenna",
        facebook: "https://go.ridgeandfalls.com/signupnow",
        metaAds: "https://go.ridgeandfalls.com/promo",
        instagram: "https://go.ridgeandfalls.com/booknow",
        tiktok: "https://go.ridgeandfalls.com/book",
        live: true,
        metaTags: true,
    },
    {
        name: "Selah Place",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1ooRi-ofa0AXNEbjD6bgLi9x2a1Z4zfKY53r_c17VeFo/edit?usp=sharing",
        manager: "Alicia",
        facebook: "https://bio.selah.place/visitnow",
        instagram: "https://bio.selah.place/booknow",
        metaAds: "https://bio.selah.place/signup",
        live: true,
        metaTags: true,
    },
    {
        name: "Starlight Haven Hot Springs",
        platform: "GoHighLevel",
        manager: "Charlotte",
        doc: "https://docs.google.com/document/d/1AC48qsDquAUyg45fQIl37mqF_kFv3ncVuhnJk0jGFYk/edit#heading=h.em57ir5cd6ty",
        instagram: "https://bio.visitstarlight.com/bookdirect",
        facebook: "https://book.visitstarlight.com/treehouse",
        metaTags: true,
        live: true,
    },
    {
        name: "Starlight Haven Weiss Lake",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1AC48qsDquAUyg45fQIl37mqF_kFv3ncVuhnJk0jGFYk/edit#heading=h.em57ir5cd6ty",
        manager: "Charlotte",
        facebook: "https://go.visitstarlight.com/promotionform",
        live: true,
        metaTags: true,
    },
    {
        name: "Stay On 30A",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1dXDBVL8YZY9OohR0AqJMKXrwYUnqRkPrxIVQy86BBgU/edit?usp=sharing",
        manager: "Charlotte",
        facebook: "https://book.stayson30a.com/booknow",
        metaAds: "https://links.stayson30a.com/signup-fb",
        instagram: "https://bio.stayon30a.com/booknow",
        live: true,
        metaTags: true,
    },
    {
        name: "Stay Saluda NC",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1w5DReTN5aB5lHKqbQOwMT42CILiiOtTA2ESsUp_jfo0/edit?usp=sharing",
        manager: "Makenna",
        facebook: "https://links.staysaluda.com/book",
        instagram: "https://bio.staysaluda.com/links",
        metaAds: "https://go.staysaluda.com/links",
        tiktok: "https://links.staysaluda.com/go",
        live: true,
        metaTags: true,
    },
    {
        name: "Stay Southern Illinois",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1hd2YuTgQ_sIjMp74gFeM2tT3JpIkaBerVj6q6tmKVko/edit?tab=t.0#heading=h.mruxqwudpn4g",
        manager: "Chiara",
        facebook: "https://go.staysouthernillinois.com/visitnow",
        metaAds: "https://go.staysouthernillinois.com/staynow",
        instagram: "https://go.staysouthernillinois.com/booknow",
        live: true,
        metaTags: true,
    },
    {
        name: "Stay With Branch",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/u/0/d/1xCsPoJ5ZsMrpiSgQNgX_glclHe5GnESil-TMv8mkZ7Q/edit",
        manager: "Charlotte",
        facebook: "https://go.gostaywithbranch.com/signup",
        instagram: "https://bio.gostaywithbranch.com/info",
        metaAds: "https://go.gostaywithbranch.com/signuptoday",
        tiktok: "https://links.gostaywithbranch.com/info",
        live: true,
        metaTags: true,
    },
    {
        name: "StayLuxe",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1Om_bYJvtUlHlJnnsNLGg-n2wvQLCDSHuCOShSu0X5UY/edit?tab=t.0",
        manager: "Nicole",
        facebook: "https://book.gostayluxevacations.com/book-483242",
        metaAds: "https://bio.gostayluxevacations.com/signup-103169",
        tiktok: "https://links.gostayluxevacations.com/book",
        live: true,
        metaTags: true,
    },
    {
        name: "Sunapee Stays",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1rHWipCl0dQsaSvkfv1NUrpGS_a0jjIQDsbvEGyyYOyg/edit?usp=drive_link",
        manager: "Charlotte",
        facebook: "https://go.sunapeestays.com/signup",
        metaAds: "https://go.sunapeestays.com/signupnow",
        instagram: "https://go.sunapeestays.com/booknow",
        live: true,
        metaTags: true,
    },
    {
        name: "Tàberg Falls",
        platform: "Netlify",
        doc: "https://docs.google.com/document/d/1VqzzoQDtUM51FmSlKBcouFNdC9QEE3ke_rBo2KoViaQ/edit?usp=sharing",
        manager: "Alicia",
        facebook: "https://bio.tabergfalls.com/visitnow",
        metaAds: "https://bio.tabergfalls.com/fb-signup",
        instagram: "https://bio.tabergfalls.com/booknow",
        live: true,
        metaTags: true,
    },
    {
        name: "The Cohost Company",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1a3U3GfVABQdpt5rzwqrIZ9jUOZm91pW9LjTcDNtTzoA/edit?usp=sharing",
        manager: "Makenna",
        facebook: "https://bio.gocohostcompany.com/go",
        instagram: "https://bio.gocohostcompany.com/links",
        metaAds: "https://go.gocohostcompany.com/book",
        live: true,
        metaTags: true,
    },
    {
        name: "The Outpost",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1oRdmIVZw-xYHbuIwxV0q8z1qreLQh82gZ8Wm8ND39Qk/edit?usp=sharing",
        manager: "Ananya",
        facebook: "https://bio.outpostgrandcanyon.com/signup",
        metaAds: "https://bio.outpostgrandcanyon.com/promotion-fb",
        instagram: "https://bio.outpostgrandcanyon.com/booknow",
        tiktok: "https://bio.outpostgrandcanyon.com/links",
        live: true,
        metaTags: true,
    },
    {
        name: "Three Suns Cabins",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1AMrNiuw-ti5WAzB85g-nHz8AzGxuPKNYwzGZOECPWz4/edit?tab=t.0#heading=h.mruxqwudpn4g",
        manager: "Ananya",
        facebook: "https://go.threesunscabins.com/booknow",
        instagram: "https://bio.threesunscabins.com/booknow",
        metaAds: "https://link.threesunscabins.com/booknow",
        tiktok: "https://link.threesunscabins.com/book",
        live: true,
        metaTags: true,
    },
    {
        name: "Treetop Escapes",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1oLYn5iQv6udTNr_BEC6cTI3x37Vds_t_SIrxEmZe_UY/edit?usp=sharing",
        manager: "Makenna",
        facebook: "https://go.staytreetopescapes.com/booknow",
        instagram: "https://bio.staytreetopescapes.com/info",
        metaAds: "https://go.staytreetopescapes.com/sign-up",
        tiktok: "https://links.staytreetopescapes.com/booknow",
        live: true,
        metaTags: true,
    },
    {
        name: "Treetop Hideaways",
        platform: "Netlify",
        manager: "Kristal",
        upcoming: true,
    },
    {
        name: "Tuxedo Falls",
        platform: "GoHighLevel",
        doc: "https://docs.google.com/document/d/1kPGBrYcD356fDdiM2qobplR22-QVBkB1UT4C9MfasQA/edit?tab=t.0",
        manager: "Chiara",
        facebook: "https://go.tuxedofalls.com/visitnow",
        metaAds: "https://go.tuxedofalls.com/staynow",
        instagram: "https://go.tuxedofalls.com/staywithus",
        tiktok: "https://go.tuxedofalls.com/visitnow-1029",
        live: true,
        metaTags: true,
    },
    {
        name: "Walden Retreats",
        platform: "Netlify",
        manager: "Ananya",
        design: "design2",
        doc: "https://docs.google.com/document/d/1JMJ_YPFURRwJcu21n_Kr9SV8sITrCrmqWRiu_yYFwqc/edit?tab=t.0#heading=h.mruxqwudpn4g",
        domain: "bio.waldenretreats.com",
        metaTags: true,
        live: true,
    },
];

export const SEED_SECTIONS: PromptSection[] = [
    {
        id: "configurations",
        title: "Configurations",
        prompts: [
            {
                id: "channel-landing-pages",
                title: "Connect GHL Forms from Netlify",
                text: "The main page should have the slug /booknow\n\nAdditional pages are:\n\n/signupnow\n/booking\n/promo\n\nAll pages are identical to each other.\n\nThe forms on each of these pages need to be tagged correctly when submitting:\n\n/booknow    instagram-ai-landing-page\n/signupnow  facebook-ai-landing-page\n/booking    meta-ads-ai-landing-page\n/promo      tiktok-ai-landing-page\n\nso that it can connect to GoHighLevel correctly.",
                use: "Builds the four channel pages with their GoHighLevel form tags.",
            },
            {
                id: "meta-tag-mue79ztl",
                title: "Meta Tag",
                text: "1. install the meta pixel code on all pages of the funnel\n2. When they submit a lead / land on the thank you page send a lead event to the meta pixel\n\n\n[Insert Meta Pixel Code]",
            },
        ],
    },
    {
        id: "optimization-mud5q45d",
        title: "Optimization",
        prompts: [
            {
                id: "30-day-cache-history-mudbq6wt",
                title: "30 day cache history",
                text: "Create a 30-day cache for this landing page and configure the caching through the netlify.toml file.",
            },
        ],
    },
    {
        id: "rer-mue53tjq",
        title: "rer",
        prompts: [],
    },
];
