import { ConfigError, cleanText, jsonError, readJson, reportingDb, accessTokenFrom, verifyCaller, recordAccess, viewerOf } from "../lib/reporting.mts";

/**
 * One request and its full history.
 *
 * ── WHY THE REFERENCE IS NOT ENOUGH ON ITS OWN ──────────────────────────────
 * "REQ-1004" is guessable by anyone who has ever seen "REQ-1003", so the lookup is
 * `reference` AND `client_slug`, with the slug taken from the verified caller and never from
 * the body. A reference that belongs to another client gets the same 404 as one that does
 * not exist at all: a different answer for the two would turn this into a way to count how
 * many requests every other client has raised.
 *
 * ── WHY route_failed EVENTS ARE NOT SENT ────────────────────────────────────
 * `route_failed` means the topic had no Asana board or no default assignee, so the brain
 * refused to open a task with nobody's name on it and told the account manager instead. That
 * is our problem being handled, and its body carries our internals. help-model.ts already
 * leaves the kind out of CLIENT_VISIBLE_EVENTS, but a screen filtering a row it was sent is
 * one refactor away from showing it. It is filtered here so it is never in the browser at
 * all. The ticket simply stays at "Received" for the client, which is true.
 *
 * `team_update` IS sent: it is an update written for them, and actorName() in help-model.ts
 * puts the name of whoever wrote it on the byline.
 *
 * POST application/json { slug, reference } + Authorization: Bearer <session token> -> { ticket, events: [...] }
 */

/** Kept in step with ticket-create.mts and ticket-withdraw.mts, which hand back the same row.
 *  The internal routing columns - tenant_id, portal_client_id, asana_task_gid, asana_task_url,
 *  asana_project_gid, derived_subject, routed_at, route_error - are absent by construction
 *  rather than stripped afterwards, so a new column has to be added here on purpose before a
 *  client can ever see it. */
const TICKET_COLUMNS =
    "id, reference, topic, title, status, created_at, detail, property, needed_by, image_count, drive_folder_url, client_name, submitted_by, submitted_by_name, assignee_name, assignee_email, account_manager_email, promised_date, completed_at, completed_by, withdrawn_at, withdrawn_by";

/** `mirrored_to_asana` is deliberately not among them: whether we managed to copy an update
 *  into Asana is a fact about our plumbing, not about the client's request. */
const EVENT_COLUMNS = "id, kind, body, actor_email, actor_name, created_at";

/** One request's timeline. Generous, because a long-running job with a lot of updates is
 *  exactly the one a client scrolls, and cheap, because it is a single ticket. */
const MAX_EVENTS = 300;

/** "REQ-1004". Generated by a sequence in the database, so the shape is fixed and checking it
 *  here keeps a hand-typed reference from reaching the query at all. */
const REFERENCE = /^REQ-\d{1,12}$/;

export default async (req: Request) => {
    if (req.method !== "POST") return new Response("Method not allowed", { status: 405 });

    const parsed = await readJson<{ slug?: unknown; accessToken?: unknown; reference?: unknown }>(req);
    if (!parsed.ok) return parsed.response;

    try {
        const gate = await verifyCaller(String(parsed.body.slug ?? ""), accessTokenFrom(req, parsed.body));
        if (!gate.ok) return jsonError(gate.status, gate.error, gate.reason);

        const reference = cleanText(parsed.body.reference, 40).toUpperCase();
        if (!REFERENCE.test(reference)) return jsonError(400, "That is not a request reference.");

        const db = reportingDb();

        const { data: ticket, error } = await db
            .from("tickets")
            .select(TICKET_COLUMNS)
            .eq("reference", reference)
            .eq("client_slug", gate.caller.slug)
            .maybeSingle();

        if (error) {
            console.error("[ticket-detail] read failed", error.message);
            return jsonError(500, "Could not load that request.");
        }
        if (!ticket) return jsonError(404, "We could not find a request with that reference.");

        const { data: events, error: eventsErr } = await db
            .from("ticket_events")
            .select(EVENT_COLUMNS)
            .eq("ticket_id", (ticket as { id: string }).id)
            .neq("kind", "route_failed")
            .order("created_at", { ascending: true })
            .limit(MAX_EVENTS);

        if (eventsErr) {
            // The ticket is the answer; the timeline is the detail on it. Losing the timeline
            // is worth an empty list and a log line, not an error page over a request the
            // client can otherwise read.
            console.error("[ticket-detail] timeline read failed", eventsErr.message, reference);
        }

        // On the record for staff, with the reference, so "who read REQ-2418"
        // has an answer. After the 404 decision, so a probe for a reference
        // that is not this client's records nothing.
        await recordAccess(gate, "ticket-detail", String((ticket as { reference?: unknown }).reference ?? "") || null);

        return Response.json({ viewer: viewerOf(gate), ticket, events: events ?? [] });
    } catch (err) {
        if (err instanceof ConfigError) {
            console.error("[ticket-detail] not configured", err.message);
            return jsonError(500, "The help centre is not configured. Ask your account manager to tell the web team.");
        }
        console.error("[ticket-detail] unexpected failure", err instanceof Error ? err.message : String(err));
        return jsonError(500, "Something went wrong at our end.");
    }
};
